# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/descontos.ui'
#
# Created: Sun Apr 21 18:20:18 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 400)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 531, 151))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 501, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cp_drvalor = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cp_drvalor.setMaximum(999999999.99)
        self.cp_drvalor.setObjectName("cp_drvalor")
        self.horizontalLayout.addWidget(self.cp_drvalor)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cp_drjuros = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.cp_drjuros.setMaximum(100.0)
        self.cp_drjuros.setObjectName("cp_drjuros")
        self.horizontalLayout.addWidget(self.cp_drjuros)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cp_drmeses = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.cp_drmeses.setMinimum(1)
        self.cp_drmeses.setMaximum(9999)
        self.cp_drmeses.setObjectName("cp_drmeses")
        self.horizontalLayout.addWidget(self.cp_drmeses)
        self.bt_drcalc = QtGui.QToolButton(self.verticalLayoutWidget)
        self.bt_drcalc.setObjectName("bt_drcalc")
        self.horizontalLayout.addWidget(self.bt_drcalc)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lb_dr_resultado = QtGui.QLabel(self.groupBox)
        self.lb_dr_resultado.setGeometry(QtCore.QRect(30, 110, 471, 16))
        self.lb_dr_resultado.setObjectName("lb_dr_resultado")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 521, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 543, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cp_drcvalor = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.cp_drcvalor.setMaximum(99999999.0)
        self.cp_drcvalor.setObjectName("cp_drcvalor")
        self.horizontalLayout_2.addWidget(self.cp_drcvalor)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.cp_drcjuros = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.cp_drcjuros.setMaximum(100.0)
        self.cp_drcjuros.setObjectName("cp_drcjuros")
        self.horizontalLayout_2.addWidget(self.cp_drcjuros)
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.cp_drcmeses = QtGui.QSpinBox(self.horizontalLayoutWidget_2)
        self.cp_drcmeses.setMinimum(1)
        self.cp_drcmeses.setMaximum(9999)
        self.cp_drcmeses.setObjectName("cp_drcmeses")
        self.horizontalLayout_2.addWidget(self.cp_drcmeses)
        self.bt_drccalc = QtGui.QToolButton(self.horizontalLayoutWidget_2)
        self.bt_drccalc.setObjectName("bt_drccalc")
        self.horizontalLayout_2.addWidget(self.bt_drccalc)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lb_drc_resultado = QtGui.QLabel(self.groupBox_2)
        self.lb_drc_resultado.setGeometry(QtCore.QRect(20, 110, 471, 16))
        self.lb_drc_resultado.setObjectName("lb_drc_resultado")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Desconto Racional", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Valor ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Juros", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Qtd de Meses", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_drcalc.setText(QtGui.QApplication.translate("Form", "Calcular DR", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_dr_resultado.setText(QtGui.QApplication.translate("Form", "Resultado Desconto Racional: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Desconto Racional Composto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Valor ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Juros", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Qtd de Meses", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_drccalc.setText(QtGui.QApplication.translate("Form", "Calcular DRC", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_drc_resultado.setText(QtGui.QApplication.translate("Form", "Resultado Desconto Racional Composto: ", None, QtGui.QApplication.UnicodeUTF8))

