# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/mainwindow.ui'
#
# Created: Sun Apr 21 18:20:18 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 440)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(550, 440))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tbCalculos = QtGui.QTabWidget(self.gridLayoutWidget)
        self.tbCalculos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCalculos.sizePolicy().hasHeightForWidth())
        self.tbCalculos.setSizePolicy(sizePolicy)
        self.tbCalculos.setElideMode(QtCore.Qt.ElideNone)
        self.tbCalculos.setTabsClosable(False)
        self.tbCalculos.setMovable(False)
        self.tbCalculos.setObjectName("tbCalculos")
        self.tabJurosComposto = QtGui.QWidget()
        self.tabJurosComposto.setObjectName("tabJurosComposto")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabJurosComposto)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 527, 341))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(True)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.cpValor = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.cpValor.setMaximum(999999.99)
        self.cpValor.setObjectName("cpValor")
        self.gridLayout_3.addWidget(self.cpValor, 1, 0, 1, 1)
        self.cpDataFim = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.cpDataFim.setObjectName("cpDataFim")
        self.gridLayout_3.addWidget(self.cpDataFim, 1, 2, 1, 1)
        self.cpDataInicio = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.cpDataInicio.setObjectName("cpDataInicio")
        self.gridLayout_3.addWidget(self.cpDataInicio, 1, 1, 1, 1)
        self.cpJuros = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.cpJuros.setMaximum(100.0)
        self.cpJuros.setObjectName("cpJuros")
        self.gridLayout_3.addWidget(self.cpJuros, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMouseTracking(True)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMouseTracking(True)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMouseTracking(True)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.cpTabela = QtGui.QTableView(self.gridLayoutWidget_2)
        self.cpTabela.setObjectName("cpTabela")
        self.gridLayout_2.addWidget(self.cpTabela, 4, 0, 1, 1)
        self.btCalculaJuros = QtGui.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btCalculaJuros.sizePolicy().hasHeightForWidth())
        self.btCalculaJuros.setSizePolicy(sizePolicy)
        self.btCalculaJuros.setObjectName("btCalculaJuros")
        self.gridLayout_2.addWidget(self.btCalculaJuros, 3, 0, 1, 1)
        self.lbFormula = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lbFormula.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbFormula.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFormula.setObjectName("lbFormula")
        self.gridLayout_2.addWidget(self.lbFormula, 2, 0, 1, 1)
        self.tbCalculos.addTab(self.tabJurosComposto, "")
        self.gridLayout.addWidget(self.tbCalculos, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        self.menuAqruivo = QtGui.QMenu(self.menubar)
        self.menuAqruivo.setObjectName("menuAqruivo")
        self.menuSobre = QtGui.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        self.menuOp_es_2 = QtGui.QMenu(self.menubar)
        self.menuOp_es_2.setObjectName("menuOp_es_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.acSalvarResultado = QtGui.QAction(MainWindow)
        self.acSalvarResultado.setObjectName("acSalvarResultado")
        self.acSair = QtGui.QAction(MainWindow)
        self.acSair.setObjectName("acSair")
        self.acCalcular = QtGui.QAction(MainWindow)
        self.acCalcular.setObjectName("acCalcular")
        self.acSobre = QtGui.QAction(MainWindow)
        self.acSobre.setObjectName("acSobre")
        self.acQT = QtGui.QAction(MainWindow)
        self.acQT.setObjectName("acQT")
        self.acSalvarValores = QtGui.QAction(MainWindow)
        self.acSalvarValores.setObjectName("acSalvarValores")
        self.acLerValores = QtGui.QAction(MainWindow)
        self.acLerValores.setObjectName("acLerValores")
        self.actionJuros_Simples = QtGui.QAction(MainWindow)
        self.actionJuros_Simples.setObjectName("actionJuros_Simples")
        self.actionFRC = QtGui.QAction(MainWindow)
        self.actionFRC.setObjectName("actionFRC")
        self.actionCalculo_de_Boletos = QtGui.QAction(MainWindow)
        self.actionCalculo_de_Boletos.setObjectName("actionCalculo_de_Boletos")
        self.acRoundValues = QtGui.QAction(MainWindow)
        self.acRoundValues.setCheckable(True)
        self.acRoundValues.setChecked(False)
        self.acRoundValues.setObjectName("acRoundValues")
        self.acCalcData = QtGui.QAction(MainWindow)
        self.acCalcData.setObjectName("acCalcData")
        self.menuAqruivo.addAction(self.acSair)
        self.menuAqruivo.addSeparator()
        self.menuSobre.addAction(self.acSobre)
        self.menuSobre.addSeparator()
        self.menuSobre.addAction(self.acQT)
        self.menuOp_es_2.addAction(self.acRoundValues)
        self.menuOp_es_2.addSeparator()
        self.menuOp_es_2.addAction(self.acCalcData)
        self.menubar.addAction(self.menuAqruivo.menuAction())
        self.menubar.addAction(self.menuOp_es_2.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tbCalculos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Aplicativo de Calculos de Juros:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Insira Valor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Data de início:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Data de Vencimento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Insira a % de Juros:", None, QtGui.QApplication.UnicodeUTF8))
        self.btCalculaJuros.setText(QtGui.QApplication.translate("MainWindow", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFormula.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCalculos.setTabText(self.tbCalculos.indexOf(self.tabJurosComposto), QtGui.QApplication.translate("MainWindow", "Juros Compostos", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAqruivo.setTitle(QtGui.QApplication.translate("MainWindow", "Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSobre.setTitle(QtGui.QApplication.translate("MainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOp_es_2.setTitle(QtGui.QApplication.translate("MainWindow", "Opções", None, QtGui.QApplication.UnicodeUTF8))
        self.acSalvarResultado.setText(QtGui.QApplication.translate("MainWindow", "Salvar Resultado", None, QtGui.QApplication.UnicodeUTF8))
        self.acSair.setText(QtGui.QApplication.translate("MainWindow", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.acCalcular.setText(QtGui.QApplication.translate("MainWindow", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.acSobre.setText(QtGui.QApplication.translate("MainWindow", "Sobre..", None, QtGui.QApplication.UnicodeUTF8))
        self.acQT.setText(QtGui.QApplication.translate("MainWindow", "QT License", None, QtGui.QApplication.UnicodeUTF8))
        self.acSalvarValores.setText(QtGui.QApplication.translate("MainWindow", "Salvar Valores", None, QtGui.QApplication.UnicodeUTF8))
        self.acLerValores.setText(QtGui.QApplication.translate("MainWindow", "Ler Valores", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJuros_Simples.setText(QtGui.QApplication.translate("MainWindow", "Juros Simples", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFRC.setText(QtGui.QApplication.translate("MainWindow", "FRC", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculo_de_Boletos.setText(QtGui.QApplication.translate("MainWindow", "Calculo de Boletos", None, QtGui.QApplication.UnicodeUTF8))
        self.acRoundValues.setText(QtGui.QApplication.translate("MainWindow", "Arredondar Valores", None, QtGui.QApplication.UnicodeUTF8))
        self.acCalcData.setText(QtGui.QApplication.translate("MainWindow", "Calculadora de Datas", None, QtGui.QApplication.UnicodeUTF8))

